### ISSUE TITLE
Rapidoc does not support headers with only content and no schema

### ISSUE THREAD

**Issue by ghilainm** [rapi-doc/RapiDoc#693]
The following error is shown in the console when only content is specified and no schema for headers.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at unpkg.com/rapidoc@9.2.0/dist/rapidoc-min.js:2886:26
    at Array.map (<anonymous>)
    at ne.responseHeaderListTemplate (unpkg.com/rapidoc@9.2.0/dist/rapidoc-min.js:2880:13)
    at unpkg.com/rapidoc@9.2.0/dist/rapidoc-min.js:2860:134
    at Array.map (<anonymous>)
    at ne.responseTemplate (unpkg.com/rapidoc@9.2.0/dist/rapidoc-min.js:2856:37)
    at ne.render (unpkg.com/rapidoc@9.2.0/dist/rapidoc-min.js:2839:16)
    at ne.update (unpkg.com/rapidoc@9.2.0/dist/rapidoc-min.js:2:14853)
    at ne.performUpdate (unpkg.com/rapidoc@9.2.0/dist/rapidoc-min.js:2:6102)
    at ne.scheduleUpdate (unpkg.com/rapidoc@9.2.0/dist/rapidoc-min.js:2:5749)
```

Example:

```
components:
  headers:
    my-header:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MySchema'
      description: whatever
      required: true
```

Snippet from openapi spec:

For more complex scenarios, the [content](https://swagger.io/specification/#parameter-content) property can define the media type and schema of the parameter. A parameter MUST contain either a schema property, or a content property, but not both. When example or examples are provided in conjunction with the schema object, the example MUST follow the prescribed serialization strategy for the parameter.

**Comment by mrin9** [comment]
thanks for reporting, will take a look soon

**Comment by mrin9** [comment]
Tested in `v9.3.6`. This issue seems be handled in a graceful manner
