### ISSUE TITLE
TypeError: Failed to execute 'append' on 'Headers': Invalid name

### ISSUE THREAD

**Issue by bjornharvold** [rapi-doc/RapiDoc#836]
Hi Team RapiDoc!

Thank you for an absolute awesome Web Component that makes me look like a pro 🦸‍♂️

Having an issue with applying basic auth header. I looked at your test site with auth examples. Our config is identical IMHO.

I enter valid credentials that work fine when applied in Postman. 

The error occurs when clicking the "Try" button.

```
Uncaught (in promise) TypeError: Failed to execute 'append' on 'Headers': Invalid name
    at api-request.js:1116:1
    at Array.forEach (<anonymous>)
    at ne.onTryClick (api-request.js:1116:1)
    at Z.handleEvent (rapidoc-min.js:2:14067)
```

Please let me know if this is an issue or if my config is incorrect. Guessing the latter 🙁

[openapi-spec.json.zip](https://github.com/rapi-doc/RapiDoc/files/9791861/openapi-spec.json.zip)

**Comment by ramiel** [comment]
I have the same problem. Did you reach any conclusion maybe?

**Comment by ramiel** [comment]
Actually I did. It's important to not specify a `name` property in the security scheme

**Comment by bjornharvold** [comment]
Hi @ramiel 

Good detective work 🦸‍♂️ My spec is auto generated. Is not specifying a name working for you and what are the side-effects of not having a name there for other tools do you think?

🍺🍿

**Comment by ramiel** [comment]
No important side effect. The name was shown in the interface but also used for the header. To have a proper interface you can use the `description` field
